#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Art_Painting06

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Art_Painting06.Art_Painting06_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AArt_Painting06_C final : public ABuildingDeco
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Art_Painting06_C">();
	}
	static class AArt_Painting06_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AArt_Painting06_C>();
	}
};
static_assert(alignof(AArt_Painting06_C) == 0x1182A000, "Wrong alignment on AArt_Painting06_C");
static_assert(sizeof(AArt_Painting06_C) == 0x1182A000, "Wrong size on AArt_Painting06_C");

}

