#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaHitPointBar

#include "Basic.hpp"

#include "AthenaHitPointBar_classes.hpp"
#include "AthenaHitPointBar_parameters.hpp"


namespace SDK
{

// Function AthenaHitPointBar.AthenaHitPointBar_C.ExecuteUbergraph_AthenaHitPointBar
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaHitPointBar_C::ExecuteUbergraph_AthenaHitPointBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "ExecuteUbergraph_AthenaHitPointBar");

	Params::AthenaHitPointBar_C_ExecuteUbergraph_AthenaHitPointBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaHitPointBar_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Tick");

	Params::AthenaHitPointBar_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaHitPointBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAthenaHitPointBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "PreConstruct");

	Params::AthenaHitPointBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateMaxValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Max                                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaHitPointBar_C::UpdateMaxValue(float Max)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateMaxValue");

	Params::AthenaHitPointBar_C_UpdateMaxValue Parms{};

	Parms.Max = Max;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateCurrentValue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Current                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EFortHitPointModificationReason         Reason                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAthenaHitPointBar_C::UpdateCurrentValue(float Current, EFortHitPointModificationReason Reason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateCurrentValue");

	Params::AthenaHitPointBar_C_UpdateCurrentValue Parms{};

	Parms.Current = Current;
	Parms.Reason = Reason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Update Fill Bar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::Update_Fill_Bar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Update Fill Bar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateCurrentValueWithoutReason
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Current                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaHitPointBar_C::UpdateCurrentValueWithoutReason(float Current)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateCurrentValueWithoutReason");

	Params::AthenaHitPointBar_C_UpdateCurrentValueWithoutReason Parms{};

	Parms.Current = Current;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Initialize Bar
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::Initialize_Bar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Initialize Bar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Update Delta Bar
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::Update_Delta_Bar()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Update Delta Bar");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.Update
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "Update");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateVolatileForUpdate
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::UpdateVolatileForUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateVolatileForUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateHealthType
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaHitPointBar_C::UpdateHealthType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateHealthType");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaHitPointBar.AthenaHitPointBar_C.UpdateDBNOState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsDBNO                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UAthenaHitPointBar_C::UpdateDBNOState(bool bIsDBNO)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaHitPointBar_C", "UpdateDBNOState");

	Params::AthenaHitPointBar_C_UpdateDBNOState Parms{};

	Parms.bIsDBNO = bIsDBNO;

	UObject::ProcessEvent(Func, &Parms);
}

}

