#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BannerLibrary

#include "Basic.hpp"

#include "BannerLibrary_classes.hpp"
#include "BannerLibrary_parameters.hpp"


namespace SDK
{

// Function BannerLibrary.BannerLibrary_C.GenericUpdateMaterial
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Target                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         BannerIcon                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     BG_PrimaryColor                                        (Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     BG_SecondaryColor                                      (Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         ShapeIcon                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::GenericUpdateMaterial(class UMaterialInstanceDynamic* Target, class UTexture* BannerIcon, const struct FLinearColor& BG_PrimaryColor, const struct FLinearColor& BG_SecondaryColor, class UTexture* ShapeIcon, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "GenericUpdateMaterial");

	Params::BannerLibrary_C_GenericUpdateMaterial Parms{};

	Parms.Target = Target;
	Parms.BannerIcon = BannerIcon;
	Parms.BG_PrimaryColor = std::move(BG_PrimaryColor);
	Parms.BG_SecondaryColor = std::move(BG_SecondaryColor);
	Parms.ShapeIcon = ShapeIcon;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BannerLibrary.BannerLibrary_C.UpdateBannerColorOnMaterial
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     PrimaryBGColor                                         (Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     SecondaryBGColor                                       (Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::UpdateBannerColorOnMaterial(class UMaterialInstanceDynamic* Material, const struct FLinearColor& PrimaryBGColor, const struct FLinearColor& SecondaryBGColor, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "UpdateBannerColorOnMaterial");

	Params::BannerLibrary_C_UpdateBannerColorOnMaterial Parms{};

	Parms.Material = Material;
	Parms.PrimaryBGColor = std::move(PrimaryBGColor);
	Parms.SecondaryBGColor = std::move(SecondaryBGColor);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BannerLibrary.BannerLibrary_C.UpdateBannerIconOnMaterial
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture*                         Icon                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::UpdateBannerIconOnMaterial(class UMaterialInstanceDynamic* Material, class UTexture* Icon, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "UpdateBannerIconOnMaterial");

	Params::BannerLibrary_C_UpdateBannerIconOnMaterial Parms{};

	Parms.Material = Material;
	Parms.Icon = Icon;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BannerLibrary.BannerLibrary_C.UpdateBannerMeshMaterial_New
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material_Instance_Dynamic                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UseIconMask                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class AFortPlayerState*                 InstigatorPlayerState                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::UpdateBannerMeshMaterial_New(class UMaterialInstanceDynamic* Material_Instance_Dynamic, bool UseIconMask, class AFortPlayerState* InstigatorPlayerState, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "UpdateBannerMeshMaterial_New");

	Params::BannerLibrary_C_UpdateBannerMeshMaterial_New Parms{};

	Parms.Material_Instance_Dynamic = Material_Instance_Dynamic;
	Parms.UseIconMask = UseIconMask;
	Parms.InstigatorPlayerState = InstigatorPlayerState;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BannerLibrary.BannerLibrary_C.UpdateMaterial_New
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UImage*                           Banner_material                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FFortHomeBaseInfo                Image_info                                             (Parm)
// bool                                    Is_Icon                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::UpdateMaterial_New(class UImage* Banner_material, const struct FFortHomeBaseInfo& Image_info, bool Is_Icon, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "UpdateMaterial_New");

	Params::BannerLibrary_C_UpdateMaterial_New Parms{};

	Parms.Banner_material = Banner_material;
	Parms.Image_info = std::move(Image_info);
	Parms.Is_Icon = Is_Icon;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BannerLibrary.BannerLibrary_C.Get Icon Texture and Colors
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           BannerIconId                                           (Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           BannerColorId                                          (Parm, ZeroConstructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       Icon                                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     PrimaryColor                                           (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     Secondary_Color                                        (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::Get_Icon_Texture_and_Colors(const class FString& BannerIconId, const class FString& BannerColorId, class UObject* __WorldContext, class UTexture2D** Icon, struct FLinearColor* PrimaryColor, struct FLinearColor* Secondary_Color)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "Get Icon Texture and Colors");

	Params::BannerLibrary_C_Get_Icon_Texture_and_Colors Parms{};

	Parms.BannerIconId = std::move(BannerIconId);
	Parms.BannerColorId = std::move(BannerColorId);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Icon != nullptr)
		*Icon = Parms.Icon;

	if (PrimaryColor != nullptr)
		*PrimaryColor = std::move(Parms.PrimaryColor);

	if (Secondary_Color != nullptr)
		*Secondary_Color = std::move(Parms.Secondary_Color);
}


// Function BannerLibrary.BannerLibrary_C.UpdateBannerMeshMaterialForUniqueId_New
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material_Instance_Dynamic                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UseIconMask                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FUniqueNetIdRepl                 UniqueId                                               (Parm, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBannerLibrary_C::UpdateBannerMeshMaterialForUniqueId_New(class UMaterialInstanceDynamic* Material_Instance_Dynamic, bool UseIconMask, const struct FUniqueNetIdRepl& UniqueId, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BannerLibrary_C", "UpdateBannerMeshMaterialForUniqueId_New");

	Params::BannerLibrary_C_UpdateBannerMeshMaterialForUniqueId_New Parms{};

	Parms.Material_Instance_Dynamic = Material_Instance_Dynamic;
	Parms.UseIconMask = UseIconMask;
	Parms.UniqueId = std::move(UniqueId);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}

}

