#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BorderMinusItemInfoHeader_BrightBar

#include "Basic.hpp"

#include "BorderMinusItemInfoHeader_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-ItemInfoHeader_BrightBar.Border-ItemInfoHeader_BrightBar_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorderMinusItemInfoHeader_BrightBar_C final : public UBorderMinusItemInfoHeader_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-ItemInfoHeader_BrightBar_C">();
	}
	static class UBorderMinusItemInfoHeader_BrightBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorderMinusItemInfoHeader_BrightBar_C>();
	}
};
static_assert(alignof(UBorderMinusItemInfoHeader_BrightBar_C) == 0x000008, "Wrong alignment on UBorderMinusItemInfoHeader_BrightBar_C");
static_assert(sizeof(UBorderMinusItemInfoHeader_BrightBar_C) == 0x0000B8, "Wrong size on UBorderMinusItemInfoHeader_BrightBar_C");

}

