#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_HordeZoneLabel_Blue

#include "Basic.hpp"

#include "Border_ItemInfoHeader_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border_HordeZoneLabel_Blue.Border_HordeZoneLabel_Blue_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_HordeZoneLabel_Blue_C final : public UBorder_ItemInfoHeader_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border_HordeZoneLabel_Blue_C">();
	}
	static class UBorder_HordeZoneLabel_Blue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_HordeZoneLabel_Blue_C>();
	}
};
static_assert(alignof(UBorder_HordeZoneLabel_Blue_C) == 0x000008, "Wrong alignment on UBorder_HordeZoneLabel_Blue_C");
static_assert(sizeof(UBorder_HordeZoneLabel_Blue_C) == 0x0000B8, "Wrong size on UBorder_HordeZoneLabel_Blue_C");

}

