#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_Bang

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-Bang.Border-Bang_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_Bang_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-Bang_C">();
	}
	static class UBorder_Bang_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_Bang_C>();
	}
};
static_assert(alignof(UBorder_Bang_C) == 0x000008, "Wrong alignment on UBorder_Bang_C");
static_assert(sizeof(UBorder_Bang_C) == 0x0000B8, "Wrong size on UBorder_Bang_C");

}

