#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_SquadBonus

#include "Basic.hpp"

#include "Border_ShellTopBar_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-SquadBonus.Border-SquadBonus_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_SquadBonus_C final : public UBorder_ShellTopBar_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-SquadBonus_C">();
	}
	static class UBorder_SquadBonus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_SquadBonus_C>();
	}
};
static_assert(alignof(UBorder_SquadBonus_C) == 0x000008, "Wrong alignment on UBorder_SquadBonus_C");
static_assert(sizeof(UBorder_SquadBonus_C) == 0x0000B8, "Wrong size on UBorder_SquadBonus_C");

}

