#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FloorLamp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FloorLamp.BP_FloorLamp_C
// 0x0000 (0x1182A000 - 0x1182A000)
class ABP_FloorLamp_C final : public ABuildingProp
{
public:
	uint8                                         Pad_FC8[0x8];                                      // 0x0FC8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0FD0(0x11821D80)(Transient, DuplicateTransient)
	class USpotLightComponent*                    SpotLight1;                                        // 0x0FD8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0FE0(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Disable_light;                                     // 0x0FE8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_FE9[0x3];                                      // 0x0FE9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         LightIntensity;                                    // 0x0FEC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LightOuterConeValue;                               // 0x0FF0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LightAttenuationRadius;                            // 0x0FF4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           LightColor;                                        // 0x0FF8(0x11821300)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_FloorLamp(int32 EntryPoint);
	void Disabale_light();
	void OnDamageServer(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AController* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void ReceiveDestroyed();
	void UserConstructionScript();
	void OnRep_disable_light();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FloorLamp_C">();
	}
	static class ABP_FloorLamp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FloorLamp_C>();
	}
};
static_assert(alignof(ABP_FloorLamp_C) == 0x1182A000, "Wrong alignment on ABP_FloorLamp_C");
static_assert(sizeof(ABP_FloorLamp_C) == 0x1182A000, "Wrong size on ABP_FloorLamp_C");
static_assert(offsetof(ABP_FloorLamp_C, UberGraphFrame) == 0x000FD0, "Member 'ABP_FloorLamp_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, SpotLight1) == 0x000FD8, "Member 'ABP_FloorLamp_C::SpotLight1' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, SpotLight) == 0x000FE0, "Member 'ABP_FloorLamp_C::SpotLight' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, Disable_light) == 0x000FE8, "Member 'ABP_FloorLamp_C::Disable_light' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, LightIntensity) == 0x000FEC, "Member 'ABP_FloorLamp_C::LightIntensity' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, LightOuterConeValue) == 0x000FF0, "Member 'ABP_FloorLamp_C::LightOuterConeValue' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, LightAttenuationRadius) == 0x000FF4, "Member 'ABP_FloorLamp_C::LightAttenuationRadius' has a wrong offset!");
static_assert(offsetof(ABP_FloorLamp_C, LightColor) == 0x000FF8, "Member 'ABP_FloorLamp_C::LightColor' has a wrong offset!");

}

