#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusTextOnlyBase_XSMinusB

#include "Basic.hpp"

#include "ButtonStyleMinusTextOnlyBase_SMinusB_Blue_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-TextOnlyBase_XS-B.ButtonStyle-TextOnlyBase_XS-B_C
// 0x0000 (0x0530 - 0x0530)
class UButtonStyleMinusTextOnlyBase_XSMinusB_C final : public UButtonStyleMinusTextOnlyBase_SMinusB_Blue_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-TextOnlyBase_XS-B_C">();
	}
	static class UButtonStyleMinusTextOnlyBase_XSMinusB_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusTextOnlyBase_XSMinusB_C>();
	}
};
static_assert(alignof(UButtonStyleMinusTextOnlyBase_XSMinusB_C) == 0x000008, "Wrong alignment on UButtonStyleMinusTextOnlyBase_XSMinusB_C");
static_assert(sizeof(UButtonStyleMinusTextOnlyBase_XSMinusB_C) == 0x000530, "Wrong size on UButtonStyleMinusTextOnlyBase_XSMinusB_C");

}

