#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ButtonStyleMinusSkew

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ButtonStyle-Skew.ButtonStyle-Skew_C
// 0x0000 (0x0530 - 0x0530)
class UButtonStyleMinusSkew_C final : public UCommonButtonStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ButtonStyle-Skew_C">();
	}
	static class UButtonStyleMinusSkew_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButtonStyleMinusSkew_C>();
	}
};
static_assert(alignof(UButtonStyleMinusSkew_C) == 0x000008, "Wrong alignment on UButtonStyleMinusSkew_C");
static_assert(sizeof(UButtonStyleMinusSkew_C) == 0x000530, "Wrong size on UButtonStyleMinusSkew_C");

}

