#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Button_SkillTree_Next_L

#include "Basic.hpp"

#include "Button_SkillTree_L_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Button-SkillTree-Next-L.Button-SkillTree-Next-L_C
// 0x0000 (0x0530 - 0x0530)
class UButton_SkillTree_Next_L_C final : public UButton_SkillTree_L_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Button-SkillTree-Next-L_C">();
	}
	static class UButton_SkillTree_Next_L_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UButton_SkillTree_Next_L_C>();
	}
};
static_assert(alignof(UButton_SkillTree_Next_L_C) == 0x000008, "Wrong alignment on UButton_SkillTree_Next_L_C");
static_assert(sizeof(UButton_SkillTree_Next_L_C) == 0x000530, "Wrong size on UButton_SkillTree_Next_L_C");

}

