#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Commerce_StoreShelves_10

#include "Basic.hpp"

#include "Commerce_StoreShelves_10_classes.hpp"
#include "Commerce_StoreShelves_10_parameters.hpp"


namespace SDK
{

// Function Commerce_StoreShelves_10.Commerce_StoreShelves_10_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ACommerce_StoreShelves_10_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Commerce_StoreShelves_10_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

