#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Commerce_StoreShelves_10

#include "Basic.hpp"


namespace SDK::Params
{

// Function Commerce_StoreShelves_10.Commerce_StoreShelves_10_C.UserConstructionScript
// 0x0021 (0x0021 - 0x0000)
struct alignas(0x21) Commerce_StoreShelves_10_C_UserConstructionScript final
{
public:
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue2;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue3;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Commerce_StoreShelves_10_C_UserConstructionScript) == 0x000021, "Wrong alignment on Commerce_StoreShelves_10_C_UserConstructionScript");
static_assert(sizeof(Commerce_StoreShelves_10_C_UserConstructionScript) == 0x000021, "Wrong size on Commerce_StoreShelves_10_C_UserConstructionScript");
static_assert(offsetof(Commerce_StoreShelves_10_C_UserConstructionScript, CallFunc_Array_Add_ReturnValue) == 0x000000, "Member 'Commerce_StoreShelves_10_C_UserConstructionScript::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(Commerce_StoreShelves_10_C_UserConstructionScript, CallFunc_Array_Add_ReturnValue2) == 0x000004, "Member 'Commerce_StoreShelves_10_C_UserConstructionScript::CallFunc_Array_Add_ReturnValue2' has a wrong offset!");
static_assert(offsetof(Commerce_StoreShelves_10_C_UserConstructionScript, CallFunc_Array_Add_ReturnValue3) == 0x000008, "Member 'Commerce_StoreShelves_10_C_UserConstructionScript::CallFunc_Array_Add_ReturnValue3' has a wrong offset!");

}

