#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CryptWalls_02

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CryptWalls_02.CryptWalls_02_C
// 0x0000 (0x1182A000 - 0x1182A000)
class ACryptWalls_02_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CryptWalls_02_C">();
	}
	static class ACryptWalls_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACryptWalls_02_C>();
	}
};
static_assert(alignof(ACryptWalls_02_C) == 0x1182A000, "Wrong alignment on ACryptWalls_02_C");
static_assert(sizeof(ACryptWalls_02_C) == 0x1182A000, "Wrong size on ACryptWalls_02_C");

}

