#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Durr_Large_Storage_Box_Group_1

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Durr_Large_Storage_Box_Group_1.Durr_Large_Storage_Box_Group_1_C
// 0x0000 (0x1182A000 - 0x1182A000)
class ADurr_Large_Storage_Box_Group_1_C final : public ABuildingContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Durr_Large_Storage_Box_Group_1_C">();
	}
	static class ADurr_Large_Storage_Box_Group_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADurr_Large_Storage_Box_Group_1_C>();
	}
};
static_assert(alignof(ADurr_Large_Storage_Box_Group_1_C) == 0x1182A000, "Wrong alignment on ADurr_Large_Storage_Box_Group_1_C");
static_assert(sizeof(ADurr_Large_Storage_Box_Group_1_C) == 0x1182A000, "Wrong size on ADurr_Large_Storage_Box_Group_1_C");

}

