#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Factory_HalfWall_Transition

#include "Basic.hpp"

#include "Parent_BuildingPropWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Factory_HalfWall_Transition.Factory_HalfWall_Transition_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AFactory_HalfWall_Transition_C final : public AParent_BuildingPropWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Factory_HalfWall_Transition_C">();
	}
	static class AFactory_HalfWall_Transition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFactory_HalfWall_Transition_C>();
	}
};
static_assert(alignof(AFactory_HalfWall_Transition_C) == 0x1182A000, "Wrong alignment on AFactory_HalfWall_Transition_C");
static_assert(sizeof(AFactory_HalfWall_Transition_C) == 0x1182A000, "Wrong size on AFactory_HalfWall_Transition_C");

}

