#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Factory_8

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Factory_8.Factory_8_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AFactory_8_C final : public ABuildingPropCorner
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Factory_8_C">();
	}
	static class AFactory_8_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFactory_8_C>();
	}
};
static_assert(alignof(AFactory_8_C) == 0x1182A000, "Wrong alignment on AFactory_8_C");
static_assert(sizeof(AFactory_8_C) == 0x1182A000, "Wrong size on AFactory_8_C");

}

