#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Farm_WeatherVane_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Farm_WeatherVane_01.Farm_WeatherVane_01_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AFarm_WeatherVane_01_C final : public ABuildingProp
{
public:
	uint8                                         Pad_FC8[0x8];                                      // 0x0FC8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0FD0(0x11821D80)(Transient, DuplicateTransient)
	class UStaticMeshComponent*                   RoosterMesh;                                       // 0x0FD8(0x0008)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         RotationAmount;                                    // 0x0FE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FE4[0x4];                                      // 0x0FE4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               SecondaryMID;                                      // 0x0FE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Farm_WeatherVane_01(int32 EntryPoint);
	void OnBounceAnimationUpdate(const struct FFortBounceData& Data);
	void ReceiveTick(float DeltaSeconds);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Farm_WeatherVane_01_C">();
	}
	static class AFarm_WeatherVane_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFarm_WeatherVane_01_C>();
	}
};
static_assert(alignof(AFarm_WeatherVane_01_C) == 0x1182A000, "Wrong alignment on AFarm_WeatherVane_01_C");
static_assert(sizeof(AFarm_WeatherVane_01_C) == 0x1182A000, "Wrong size on AFarm_WeatherVane_01_C");
static_assert(offsetof(AFarm_WeatherVane_01_C, UberGraphFrame) == 0x000FD0, "Member 'AFarm_WeatherVane_01_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AFarm_WeatherVane_01_C, RoosterMesh) == 0x000FD8, "Member 'AFarm_WeatherVane_01_C::RoosterMesh' has a wrong offset!");
static_assert(offsetof(AFarm_WeatherVane_01_C, RotationAmount) == 0x000FE0, "Member 'AFarm_WeatherVane_01_C::RotationAmount' has a wrong offset!");
static_assert(offsetof(AFarm_WeatherVane_01_C, SecondaryMID) == 0x000FE8, "Member 'AFarm_WeatherVane_01_C::SecondaryMID' has a wrong offset!");

}

