#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FortMetaNavAreaDef

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass FortMetaNavAreaDef.FortMetaNavAreaDef_C
// 0x0000 (0x0050 - 0x0050)
class UFortMetaNavAreaDef_C final : public UFortMetaNavArea
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FortMetaNavAreaDef_C">();
	}
	static class UFortMetaNavAreaDef_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFortMetaNavAreaDef_C>();
	}
};
static_assert(alignof(UFortMetaNavAreaDef_C) == 0x000008, "Wrong alignment on UFortMetaNavAreaDef_C");
static_assert(sizeof(UFortMetaNavAreaDef_C) == 0x000050, "Wrong size on UFortMetaNavAreaDef_C");

}

