#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GamepadMappingInfo

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "UMG_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GamepadMappingInfo.GamepadMappingInfo_C
// 0x0128 (0x0360 - 0x0238)
class UGamepadMappingInfo_C final : public UCommonUserWidget
{
public:
	class UImage*                                 Image_Gamepad;                                     // 0x0238(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Gamepad_Buttons;                             // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Mode;                                        // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Bottom;                   // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Left_1;                   // 0x0258(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Left_2;                   // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Left_3;                   // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Right_1;                  // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Right_2;                  // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Top_1;                    // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Face_Button_Top_2;                    // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_LB;                                   // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_LB_RB;                                // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_LT;                                   // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_RB;                                   // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_RS;                                   // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_RS_Click_1;                           // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_RS_Click_2;                           // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_RT;                                   // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Select_1;                             // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Select_2;                             // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Gamepad_Start;                                // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Mode;                                         // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_Dpad_Down;                                // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_Dpad_Left;                                // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_Dpad_Right;                               // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_Dpad_Up;                                  // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_LS;                                       // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_PS4_LS_Click;                                 // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_Dpad_Down;                               // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_Dpad_Left;                               // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_Dpad_Right;                              // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_Dpad_Up;                                 // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_LS;                                      // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_Xbox_LS_Click;                                // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_PS4_LS_And_Dpad;                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_Xbox_LS_And_Dpad;                      // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Update_Displayed_Mapping(int32 platform, int32 Mode, int32 Configuration);
	void OnConfigChanged(int32 Mode, int32 Config);
	void HandleConfigChanged_Athena(int32 Mode, int32 Config);
	void HandleConfigChanged(int32 Mode, int32 Config);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GamepadMappingInfo_C">();
	}
	static class UGamepadMappingInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGamepadMappingInfo_C>();
	}
};
static_assert(alignof(UGamepadMappingInfo_C) == 0x000008, "Wrong alignment on UGamepadMappingInfo_C");
static_assert(sizeof(UGamepadMappingInfo_C) == 0x000360, "Wrong size on UGamepadMappingInfo_C");
static_assert(offsetof(UGamepadMappingInfo_C, Image_Gamepad) == 0x000238, "Member 'UGamepadMappingInfo_C::Image_Gamepad' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Image_Gamepad_Buttons) == 0x000240, "Member 'UGamepadMappingInfo_C::Image_Gamepad_Buttons' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Image_Mode) == 0x000248, "Member 'UGamepadMappingInfo_C::Image_Mode' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Bottom) == 0x000250, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Bottom' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Left_1) == 0x000258, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Left_1' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Left_2) == 0x000260, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Left_2' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Left_3) == 0x000268, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Left_3' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Right_1) == 0x000270, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Right_1' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Right_2) == 0x000278, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Right_2' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Top_1) == 0x000280, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Top_1' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Face_Button_Top_2) == 0x000288, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Face_Button_Top_2' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_LB) == 0x000290, "Member 'UGamepadMappingInfo_C::Text_Gamepad_LB' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_LB_RB) == 0x000298, "Member 'UGamepadMappingInfo_C::Text_Gamepad_LB_RB' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_LT) == 0x0002A0, "Member 'UGamepadMappingInfo_C::Text_Gamepad_LT' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_RB) == 0x0002A8, "Member 'UGamepadMappingInfo_C::Text_Gamepad_RB' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_RS) == 0x0002B0, "Member 'UGamepadMappingInfo_C::Text_Gamepad_RS' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_RS_Click_1) == 0x0002B8, "Member 'UGamepadMappingInfo_C::Text_Gamepad_RS_Click_1' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_RS_Click_2) == 0x0002C0, "Member 'UGamepadMappingInfo_C::Text_Gamepad_RS_Click_2' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_RT) == 0x0002C8, "Member 'UGamepadMappingInfo_C::Text_Gamepad_RT' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Select_1) == 0x0002D0, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Select_1' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Select_2) == 0x0002D8, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Select_2' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Gamepad_Start) == 0x0002E0, "Member 'UGamepadMappingInfo_C::Text_Gamepad_Start' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Mode) == 0x0002E8, "Member 'UGamepadMappingInfo_C::Text_Mode' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_Dpad_Down) == 0x0002F0, "Member 'UGamepadMappingInfo_C::Text_PS4_Dpad_Down' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_Dpad_Left) == 0x0002F8, "Member 'UGamepadMappingInfo_C::Text_PS4_Dpad_Left' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_Dpad_Right) == 0x000300, "Member 'UGamepadMappingInfo_C::Text_PS4_Dpad_Right' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_Dpad_Up) == 0x000308, "Member 'UGamepadMappingInfo_C::Text_PS4_Dpad_Up' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_LS) == 0x000310, "Member 'UGamepadMappingInfo_C::Text_PS4_LS' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_PS4_LS_Click) == 0x000318, "Member 'UGamepadMappingInfo_C::Text_PS4_LS_Click' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_Dpad_Down) == 0x000320, "Member 'UGamepadMappingInfo_C::Text_Xbox_Dpad_Down' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_Dpad_Left) == 0x000328, "Member 'UGamepadMappingInfo_C::Text_Xbox_Dpad_Left' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_Dpad_Right) == 0x000330, "Member 'UGamepadMappingInfo_C::Text_Xbox_Dpad_Right' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_Dpad_Up) == 0x000338, "Member 'UGamepadMappingInfo_C::Text_Xbox_Dpad_Up' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_LS) == 0x000340, "Member 'UGamepadMappingInfo_C::Text_Xbox_LS' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, Text_Xbox_LS_Click) == 0x000348, "Member 'UGamepadMappingInfo_C::Text_Xbox_LS_Click' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, VerticalBox_PS4_LS_And_Dpad) == 0x000350, "Member 'UGamepadMappingInfo_C::VerticalBox_PS4_LS_And_Dpad' has a wrong offset!");
static_assert(offsetof(UGamepadMappingInfo_C, VerticalBox_Xbox_LS_And_Dpad) == 0x000358, "Member 'UGamepadMappingInfo_C::VerticalBox_Xbox_LS_And_Dpad' has a wrong offset!");

}

