#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HordeTierResultsWidget

#include "Basic.hpp"

#include "HordeTierResultsWidget_classes.hpp"
#include "HordeTierResultsWidget_parameters.hpp"


namespace SDK
{

// Function HordeTierResultsWidget.HordeTierResultsWidget_C.InitializeMovie
// (Protected, BlueprintCallable, BlueprintEvent)

void UHordeTierResultsWidget_C::InitializeMovie()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HordeTierResultsWidget_C", "InitializeMovie");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HordeTierResultsWidget.HordeTierResultsWidget_C.Initialize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EFortCompletionResult                   Result                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHordeTierResultsWidget_C::Initialize(EFortCompletionResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HordeTierResultsWidget_C", "Initialize");

	Params::HordeTierResultsWidget_C_Initialize Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HordeTierResultsWidget.HordeTierResultsWidget_C.ChooseMediaToUse
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMediaSource*                     MediaToUse                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHordeTierResultsWidget_C::ChooseMediaToUse(class UMediaSource** MediaToUse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HordeTierResultsWidget_C", "ChooseMediaToUse");

	Params::HordeTierResultsWidget_C_ChooseMediaToUse Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (MediaToUse != nullptr)
		*MediaToUse = Parms.MediaToUse;
}


// Function HordeTierResultsWidget.HordeTierResultsWidget_C.OnEndOfMovieReached
// (Public, BlueprintCallable, BlueprintEvent)

void UHordeTierResultsWidget_C::OnEndOfMovieReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HordeTierResultsWidget_C", "OnEndOfMovieReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HordeTierResultsWidget.HordeTierResultsWidget_C.OnHandleAction
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FEventReply                      Result                                                 (Parm, OutParm)
// bool                                    bPassThrough                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UHordeTierResultsWidget_C::OnHandleAction(struct FEventReply* Result, bool* bPassThrough)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HordeTierResultsWidget_C", "OnHandleAction");

	Params::HordeTierResultsWidget_C_OnHandleAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = std::move(Parms.Result);

	if (bPassThrough != nullptr)
		*bPassThrough = Parms.bPassThrough;
}

}

