#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HuskStrength05

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HuskStrength05.HuskStrength05_C
// 0x0000 (0x0060 - 0x0060)
class UHuskStrength05_C final : public UFortNavAreaAutomatic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HuskStrength05_C">();
	}
	static class UHuskStrength05_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHuskStrength05_C>();
	}
};
static_assert(alignof(UHuskStrength05_C) == 0x000008, "Wrong alignment on UHuskStrength05_C");
static_assert(sizeof(UHuskStrength05_C) == 0x000060, "Wrong size on UHuskStrength05_C");

}

