#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemCountOverCost

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function ItemCountOverCost.ItemCountOverCost_C.ExecuteUbergraph_ItemCountOverCost
// 0x0008 (0x0008 - 0x0000)
struct ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost) == 0x000004, "Wrong alignment on ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost");
static_assert(sizeof(ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost) == 0x000008, "Wrong size on ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost");
static_assert(offsetof(ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost, EntryPoint) == 0x000000, "Member 'ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost::EntryPoint' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost, K2Node_Event_IsDesignTime) == 0x000004, "Member 'ItemCountOverCost_C_ExecuteUbergraph_ItemCountOverCost::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function ItemCountOverCost.ItemCountOverCost_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct ItemCountOverCost_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(ItemCountOverCost_C_PreConstruct) == 0x000001, "Wrong alignment on ItemCountOverCost_C_PreConstruct");
static_assert(sizeof(ItemCountOverCost_C_PreConstruct) == 0x000001, "Wrong size on ItemCountOverCost_C_PreConstruct");
static_assert(offsetof(ItemCountOverCost_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'ItemCountOverCost_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function ItemCountOverCost.ItemCountOverCost_C.Get Meets Criteria Color
// 0x0038 (0x0038 - 0x0000)
struct ItemCountOverCost_C_Get_Meets_Criteria_Color final
{
public:
	struct FLinearColor                           ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Temp_struct_Variable;                              // 0x0014(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           K2Node_Select_Default;                             // 0x0028(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemCountOverCost_C_Get_Meets_Criteria_Color) == 0x000004, "Wrong alignment on ItemCountOverCost_C_Get_Meets_Criteria_Color");
static_assert(sizeof(ItemCountOverCost_C_Get_Meets_Criteria_Color) == 0x000038, "Wrong size on ItemCountOverCost_C_Get_Meets_Criteria_Color");
static_assert(offsetof(ItemCountOverCost_C_Get_Meets_Criteria_Color, ReturnValue) == 0x000000, "Member 'ItemCountOverCost_C_Get_Meets_Criteria_Color::ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Get_Meets_Criteria_Color, Temp_bool_Variable) == 0x000010, "Member 'ItemCountOverCost_C_Get_Meets_Criteria_Color::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Get_Meets_Criteria_Color, Temp_struct_Variable) == 0x000014, "Member 'ItemCountOverCost_C_Get_Meets_Criteria_Color::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Get_Meets_Criteria_Color, CallFunc_Less_IntInt_ReturnValue) == 0x000024, "Member 'ItemCountOverCost_C_Get_Meets_Criteria_Color::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Get_Meets_Criteria_Color, K2Node_Select_Default) == 0x000028, "Member 'ItemCountOverCost_C_Get_Meets_Criteria_Color::K2Node_Select_Default' has a wrong offset!");

// Function ItemCountOverCost.ItemCountOverCost_C.Update
// 0x0078 (0x0078 - 0x0000)
struct ItemCountOverCost_C_Update final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable2;                               // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable4;                               // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_Get_Meets_Criteria_Color_ReturnValue;     // 0x0008(0x0010)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Calculate_Total_Item_Def_in_Inventory_Count; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0020(0x0028)()
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select2_Default;                            // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4A[0x2];                                       // 0x004A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDisplayName_ReturnValue;               // 0x0058(0x0018)()
	float                                         CallFunc_Conv_IntToFloat_ReturnValue2;             // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemCountOverCost_C_Update) == 0x000008, "Wrong alignment on ItemCountOverCost_C_Update");
static_assert(sizeof(ItemCountOverCost_C_Update) == 0x000078, "Wrong size on ItemCountOverCost_C_Update");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_bool_Variable) == 0x000000, "Member 'ItemCountOverCost_C_Update::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_byte_Variable) == 0x000001, "Member 'ItemCountOverCost_C_Update::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_byte_Variable2) == 0x000002, "Member 'ItemCountOverCost_C_Update::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_bool_Variable2) == 0x000003, "Member 'ItemCountOverCost_C_Update::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_byte_Variable3) == 0x000004, "Member 'ItemCountOverCost_C_Update::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, Temp_byte_Variable4) == 0x000005, "Member 'ItemCountOverCost_C_Update::Temp_byte_Variable4' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_Get_Meets_Criteria_Color_ReturnValue) == 0x000008, "Member 'ItemCountOverCost_C_Update::CallFunc_Get_Meets_Criteria_Color_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_Calculate_Total_Item_Def_in_Inventory_Count) == 0x000018, "Member 'ItemCountOverCost_C_Update::CallFunc_Calculate_Total_Item_Def_in_Inventory_Count' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, K2Node_MakeStruct_SlateColor) == 0x000020, "Member 'ItemCountOverCost_C_Update::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, K2Node_Select_Default) == 0x000048, "Member 'ItemCountOverCost_C_Update::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, K2Node_Select2_Default) == 0x000049, "Member 'ItemCountOverCost_C_Update::K2Node_Select2_Default' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_Conv_IntToFloat_ReturnValue) == 0x00004C, "Member 'ItemCountOverCost_C_Update::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_IsValid_ReturnValue) == 0x000050, "Member 'ItemCountOverCost_C_Update::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_GetDisplayName_ReturnValue) == 0x000058, "Member 'ItemCountOverCost_C_Update::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Update, CallFunc_Conv_IntToFloat_ReturnValue2) == 0x000070, "Member 'ItemCountOverCost_C_Update::CallFunc_Conv_IntToFloat_ReturnValue2' has a wrong offset!");

// Function ItemCountOverCost.ItemCountOverCost_C.Calculate Total Item Def in Inventory
// 0x0058 (0x0058 - 0x0000)
struct ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory final
{
public:
	class UFortItemDefinition*                    ItemDefinition_0;                                  // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Count_0;                                           // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TotalCount;                                        // 0x000C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortInventoryContext*                  CallFunc_GetContext_ReturnValue;                   // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UFortItem*>                      CallFunc_GetItemInstancesByDefinition_Items;       // 0x0028(0x0010)(ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItem*                              CallFunc_Array_Get_Item;                           // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetNumInStack_ReturnValue;                // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory) == 0x000008, "Wrong alignment on ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory");
static_assert(sizeof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory) == 0x000058, "Wrong size on ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, ItemDefinition_0) == 0x000000, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::ItemDefinition_0' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, Count_0) == 0x000008, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::Count_0' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, TotalCount) == 0x00000C, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::TotalCount' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, Temp_int_Array_Index_Variable) == 0x000010, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_Add_IntInt_ReturnValue) == 0x000018, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_GetContext_ReturnValue) == 0x000020, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_GetItemInstancesByDefinition_Items) == 0x000028, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_GetItemInstancesByDefinition_Items' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_Array_Get_Item) == 0x000040, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_Less_IntInt_ReturnValue) == 0x000048, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_GetNumInStack_ReturnValue) == 0x00004C, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_GetNumInStack_ReturnValue' has a wrong offset!");
static_assert(offsetof(ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory, CallFunc_Add_IntInt_ReturnValue2) == 0x000050, "Member 'ItemCountOverCost_C_Calculate_Total_Item_Def_in_Inventory::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");

}

