#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemDetailsStackCounter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "CommonUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ItemDetailsStackCounter.ItemDetailsStackCounter_C
// 0x0000 (0x322CBBB8 - 0x322CBBB8)
class UItemDetailsStackCounter_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0238(0x11821D80)(Transient, DuplicateTransient)
	class USizeBox*                               _SizeBox_;                                         // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          BorderBase;                                        // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TextCounter;                                       // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FFortMultiSizeBrush                    MultiSizeBase;                                     // 0x0258(0x11827900)(Edit, BlueprintVisible)
	struct FFortMultiSizeFont                     MultiSizeFont;                                     // 0x05B8(0x11827900)(Edit, BlueprintVisible)
	struct FFortMultiSizeMargin                   MultiSizeMargin;                                   // 0x0828(0x322CBBB8)(Edit, BlueprintVisible, NoDestructor)
	EFortBrushSize                                Brush_Size;                                        // 0x0888(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_889[0x3];                                      // 0x0889(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Count;                                             // 0x088C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          AlwaysVisible;                                     // 0x0890(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          TruncateValue;                                     // 0x0891(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_ItemDetailsStackCounter(int32 EntryPoint);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void Update(EFortBrushSize Brush_Size_0, int32 Count_0);
	void Set_Stack_Count(int32 Count_0);
	void Refresh_Visibility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemDetailsStackCounter_C">();
	}
	static class UItemDetailsStackCounter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemDetailsStackCounter_C>();
	}
};
static_assert(alignof(UItemDetailsStackCounter_C) == 0x322CBBB8, "Wrong alignment on UItemDetailsStackCounter_C");
static_assert(sizeof(UItemDetailsStackCounter_C) == 0x322CBBB8, "Wrong size on UItemDetailsStackCounter_C");
static_assert(offsetof(UItemDetailsStackCounter_C, UberGraphFrame) == 0x000238, "Member 'UItemDetailsStackCounter_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, _SizeBox_) == 0x000240, "Member 'UItemDetailsStackCounter_C::_SizeBox_' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, BorderBase) == 0x000248, "Member 'UItemDetailsStackCounter_C::BorderBase' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, TextCounter) == 0x000250, "Member 'UItemDetailsStackCounter_C::TextCounter' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, MultiSizeBase) == 0x000258, "Member 'UItemDetailsStackCounter_C::MultiSizeBase' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, MultiSizeFont) == 0x0005B8, "Member 'UItemDetailsStackCounter_C::MultiSizeFont' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, MultiSizeMargin) == 0x000828, "Member 'UItemDetailsStackCounter_C::MultiSizeMargin' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, Brush_Size) == 0x000888, "Member 'UItemDetailsStackCounter_C::Brush_Size' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, Count) == 0x00088C, "Member 'UItemDetailsStackCounter_C::Count' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, AlwaysVisible) == 0x000890, "Member 'UItemDetailsStackCounter_C::AlwaysVisible' has a wrong offset!");
static_assert(offsetof(UItemDetailsStackCounter_C, TruncateValue) == 0x000891, "Member 'UItemDetailsStackCounter_C::TruncateValue' has a wrong offset!");

}

