#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Kitchen_Griddle_02

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Kitchen_Griddle_02.Kitchen_Griddle_02_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AKitchen_Griddle_02_C final : public ABuildingContainer
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Kitchen_Griddle_02_C">();
	}
	static class AKitchen_Griddle_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AKitchen_Griddle_02_C>();
	}
};
static_assert(alignof(AKitchen_Griddle_02_C) == 0x1182A000, "Wrong alignment on AKitchen_Griddle_02_C");
static_assert(sizeof(AKitchen_Griddle_02_C) == 0x1182A000, "Wrong size on AKitchen_Griddle_02_C");

}

