#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginAccountSelect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoginAccountSelect.LoginAccountSelect_C
// 0x0000 (0x322CBBB8 - 0x322CBBB8)
class ULoginAccountSelect_C final : public UFortLoginAccountSelect
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03F0(0x11821D80)(Transient, DuplicateTransient)
	class UIconTextButton_C*                      EpicLoginButton;                                   // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      PlayStationLoginButton;                            // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UIconTextButton_C*                      XBoxLoginButton;                                   // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_LoginAccountSelect(int32 EntryPoint);
	void OnActivated();
	void BndEvt__XBoxLoginButton_K2Node_ComponentBoundEvent_2_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void BndEvt__PlayStationLoginButton_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void BndEvt__EpicLoginButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoginAccountSelect_C">();
	}
	static class ULoginAccountSelect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoginAccountSelect_C>();
	}
};
static_assert(alignof(ULoginAccountSelect_C) == 0x322CBBB8, "Wrong alignment on ULoginAccountSelect_C");
static_assert(sizeof(ULoginAccountSelect_C) == 0x322CBBB8, "Wrong size on ULoginAccountSelect_C");
static_assert(offsetof(ULoginAccountSelect_C, UberGraphFrame) == 0x0003F0, "Member 'ULoginAccountSelect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ULoginAccountSelect_C, EpicLoginButton) == 0x0003F8, "Member 'ULoginAccountSelect_C::EpicLoginButton' has a wrong offset!");
static_assert(offsetof(ULoginAccountSelect_C, PlayStationLoginButton) == 0x000400, "Member 'ULoginAccountSelect_C::PlayStationLoginButton' has a wrong offset!");
static_assert(offsetof(ULoginAccountSelect_C, XBoxLoginButton) == 0x000408, "Member 'ULoginAccountSelect_C::XBoxLoginButton' has a wrong offset!");

}

