#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mailbox_01a

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Mailbox_01a.Mailbox_01a_C.ExecuteUbergraph_Mailbox_01a
// 0x11821300 (0x11821300 - 0x0000)
struct Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0004(0x11821300)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a) == 0x11821300, "Wrong alignment on Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a");
static_assert(sizeof(Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a) == 0x11821300, "Wrong size on Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a");
static_assert(offsetof(Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a, EntryPoint) == 0x000000, "Member 'Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a::EntryPoint' has a wrong offset!");
static_assert(offsetof(Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000004, "Member 'Mailbox_01a_C_ExecuteUbergraph_Mailbox_01a::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");

}

