#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainModeItemDetailsHostPanel

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function MainModeItemDetailsHostPanel.MainModeItemDetailsHostPanel_C.ExecuteUbergraph_MainModeItemDetailsHostPanel
// 0x000C (0x000C - 0x0000)
struct MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable2;                               // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable3;                               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable4;                               // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select2_Default;                            // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel) == 0x000004, "Wrong alignment on MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel");
static_assert(sizeof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel) == 0x00000C, "Wrong size on MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, EntryPoint) == 0x000000, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::EntryPoint' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_bool_Variable) == 0x000004, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_byte_Variable) == 0x000005, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_byte_Variable2) == 0x000006, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_bool_Variable2) == 0x000007, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_bool_Variable2' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_byte_Variable3) == 0x000008, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_byte_Variable3' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, Temp_byte_Variable4) == 0x000009, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::Temp_byte_Variable4' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, K2Node_Select_Default) == 0x00000A, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel, K2Node_Select2_Default) == 0x00000B, "Member 'MainModeItemDetailsHostPanel_C_ExecuteUbergraph_MainModeItemDetailsHostPanel::K2Node_Select2_Default' has a wrong offset!");

// Function MainModeItemDetailsHostPanel.MainModeItemDetailsHostPanel_C.UpdateDescriptionVisibility
// 0x0004 (0x0004 - 0x0000)
struct MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable2;                               // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility) == 0x000001, "Wrong alignment on MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility");
static_assert(sizeof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility) == 0x000004, "Wrong size on MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility, Temp_bool_Variable) == 0x000000, "Member 'MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility, Temp_byte_Variable) == 0x000001, "Member 'MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility, Temp_byte_Variable2) == 0x000002, "Member 'MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility::Temp_byte_Variable2' has a wrong offset!");
static_assert(offsetof(MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility, K2Node_Select_Default) == 0x000003, "Member 'MainModeItemDetailsHostPanel_C_UpdateDescriptionVisibility::K2Node_Select_Default' has a wrong offset!");

}

