#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainPlayerCamera

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MainPlayerCamera.MainPlayerCamera_C
// 0x0000 (0x11821D80 - 0x11821D80)
class AMainPlayerCamera_C final : public AFortPlayerCameraBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainPlayerCamera_C">();
	}
	static class AMainPlayerCamera_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainPlayerCamera_C>();
	}
};
static_assert(alignof(AMainPlayerCamera_C) == 0x11821D80, "Wrong alignment on AMainPlayerCamera_C");
static_assert(sizeof(AMainPlayerCamera_C) == 0x11821D80, "Wrong size on AMainPlayerCamera_C");

}

