#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MetalBleachers

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MetalBleachers.MetalBleachers_C
// 0x0000 (0x1182A000 - 0x1182A000)
class AMetalBleachers_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MetalBleachers_C">();
	}
	static class AMetalBleachers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMetalBleachers_C>();
	}
};
static_assert(alignof(AMetalBleachers_C) == 0x1182A000, "Wrong alignment on AMetalBleachers_C");
static_assert(sizeof(AMetalBleachers_C) == 0x1182A000, "Wrong size on AMetalBleachers_C");

}

