#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OutpostScreenStormShieldPermissions

#include "Basic.hpp"

#include "OutpostScreenStormShieldPermissions_classes.hpp"
#include "OutpostScreenStormShieldPermissions_parameters.hpp"


namespace SDK
{

// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.ExecuteUbergraph_OutpostScreenStormShieldPermissions
// (HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOutpostScreenStormShieldPermissions_C::ExecuteUbergraph_OutpostScreenStormShieldPermissions(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "ExecuteUbergraph_OutpostScreenStormShieldPermissions");

	Params::OutpostScreenStormShieldPermissions_C_ExecuteUbergraph_OutpostScreenStormShieldPermissions Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.OnActivated
// (Event, Protected, BlueprintEvent)

void UOutpostScreenStormShieldPermissions_C::OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.UpdatePrivilagesEvent_1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PlayerIndex                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOutpostScreenStormShieldPermissions_C::UpdatePrivilagesEvent_1(int32 PlayerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "UpdatePrivilagesEvent_1");

	Params::OutpostScreenStormShieldPermissions_C_UpdatePrivilagesEvent_1 Parms{};

	Parms.PlayerIndex = PlayerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.UpdatePrivilagesEvent_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FFortTeamMemberInfo              NewTeamMemberInfo                                      (Parm)

void UOutpostScreenStormShieldPermissions_C::UpdatePrivilagesEvent_0(const struct FFortTeamMemberInfo& NewTeamMemberInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "UpdatePrivilagesEvent_0");

	Params::OutpostScreenStormShieldPermissions_C_UpdatePrivilagesEvent_0 Parms{};

	Parms.NewTeamMemberInfo = std::move(NewTeamMemberInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UOutpostScreenStormShieldPermissions_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.isPlayerAlone
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    isAlone                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOutpostScreenStormShieldPermissions_C::isPlayerAlone(bool* isAlone)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "isPlayerAlone");

	Params::OutpostScreenStormShieldPermissions_C_isPlayerAlone Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (isAlone != nullptr)
		*isAlone = Parms.isAlone;
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.UpdatePrivilages
// (Public, BlueprintCallable, BlueprintEvent)

void UOutpostScreenStormShieldPermissions_C::UpdatePrivilages()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "UpdatePrivilages");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.IsOwningPlayerOutpostOwner
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UOutpostScreenStormShieldPermissions_C::IsOwningPlayerOutpostOwner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "IsOwningPlayerOutpostOwner");

	Params::OutpostScreenStormShieldPermissions_C_IsOwningPlayerOutpostOwner Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.AddInputHandlers
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UOutpostScreenStormShieldPermissions_C::AddInputHandlers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "AddInputHandlers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.HandleBack
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PassThrough                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOutpostScreenStormShieldPermissions_C::HandleBack(bool* PassThrough)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "HandleBack");

	Params::OutpostScreenStormShieldPermissions_C_HandleBack Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PassThrough != nullptr)
		*PassThrough = Parms.PassThrough;
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.SetParent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UOutpostScreenStormShield_C*      ParentWidget                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOutpostScreenStormShieldPermissions_C::SetParent(class UOutpostScreenStormShield_C* ParentWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "SetParent");

	Params::OutpostScreenStormShieldPermissions_C_SetParent Parms{};

	Parms.ParentWidget = ParentWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OutpostScreenStormShieldPermissions.OutpostScreenStormShieldPermissions_C.CenterWidget
// (Public, BlueprintCallable, BlueprintEvent)

void UOutpostScreenStormShieldPermissions_C::CenterWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OutpostScreenStormShieldPermissions_C", "CenterWidget");

	UObject::ProcessEvent(Func, nullptr);
}

}

