#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Plant_Corn01

#include "Basic.hpp"

#include "ParentBuildingContainerBlueprint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Plant_Corn01.Plant_Corn01_C
// 0x0000 (0x1182A000 - 0x1182A000)
class APlant_Corn01_C final : public AParentBuildingContainerBlueprint_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Plant_Corn01_C">();
	}
	static class APlant_Corn01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlant_Corn01_C>();
	}
};
static_assert(alignof(APlant_Corn01_C) == 0x1182A000, "Wrong alignment on APlant_Corn01_C");
static_assert(sizeof(APlant_Corn01_C) == 0x1182A000, "Wrong size on APlant_Corn01_C");

}

