#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerTrapDiceCritChanceModCalculation

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PlayerTrapDiceCritChanceModCalculation.PlayerTrapDiceCritChanceModCalculation_C
// 0x0000 (0x0068 - 0x0068)
class UPlayerTrapDiceCritChanceModCalculation_C final : public UPlayerTrapBonusModMagnitudeCalculation
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerTrapDiceCritChanceModCalculation_C">();
	}
	static class UPlayerTrapDiceCritChanceModCalculation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerTrapDiceCritChanceModCalculation_C>();
	}
};
static_assert(alignof(UPlayerTrapDiceCritChanceModCalculation_C) == 0x000008, "Wrong alignment on UPlayerTrapDiceCritChanceModCalculation_C");
static_assert(sizeof(UPlayerTrapDiceCritChanceModCalculation_C) == 0x000068, "Wrong size on UPlayerTrapDiceCritChanceModCalculation_C");

}

