#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Recreation_CampingKayak01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Recreation_CampingKayak01.Recreation_CampingKayak01_C
// 0x0000 (0x1182A000 - 0x1182A000)
class ARecreation_CampingKayak01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Recreation_CampingKayak01_C">();
	}
	static class ARecreation_CampingKayak01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARecreation_CampingKayak01_C>();
	}
};
static_assert(alignof(ARecreation_CampingKayak01_C) == 0x1182A000, "Wrong alignment on ARecreation_CampingKayak01_C");
static_assert(sizeof(ARecreation_CampingKayak01_C) == 0x1182A000, "Wrong size on ARecreation_CampingKayak01_C");

}

