#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Reticle

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass Reticle.Reticle_C
// 0x0000 (0x0288 - 0x0288)
class UReticle_C final : public UFortReticle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Reticle_C">();
	}
	static class UReticle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReticle_C>();
	}
};
static_assert(alignof(UReticle_C) == 0x000008, "Wrong alignment on UReticle_C");
static_assert(sizeof(UReticle_C) == 0x000288, "Wrong size on UReticle_C");

}

