#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RewardListEntryType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum RewardListEntryType.RewardListEntryType
// NumValues: 0x0004
enum class ERewardListEntryType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	RewardListEntryType_MAX                  = 3,
};

}

