#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Roof_AirConditioner_01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Roof_AirConditioner_01.Roof_AirConditioner_01_C
// 0x0000 (0x1182A000 - 0x1182A000)
class ARoof_AirConditioner_01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Roof_AirConditioner_01_C">();
	}
	static class ARoof_AirConditioner_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARoof_AirConditioner_01_C>();
	}
};
static_assert(alignof(ARoof_AirConditioner_01_C) == 0x1182A000, "Wrong alignment on ARoof_AirConditioner_01_C");
static_assert(sizeof(ARoof_AirConditioner_01_C) == 0x1182A000, "Wrong size on ARoof_AirConditioner_01_C");

}

