#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TabGamePadConfig

#include "Basic.hpp"

#include "TabGamePadConfig_classes.hpp"
#include "TabGamePadConfig_parameters.hpp"


namespace SDK
{

// Function TabGamePadConfig.TabGamePadConfig_C.ExecuteUbergraph_TabGamePadConfig
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTabGamePadConfig_C::ExecuteUbergraph_TabGamePadConfig(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "ExecuteUbergraph_TabGamePadConfig");

	Params::TabGamePadConfig_C_ExecuteUbergraph_TabGamePadConfig Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TabGamePadConfig.TabGamePadConfig_C.ControllerPlatformConfigChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Selected_Index                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTabGamePadConfig_C::ControllerPlatformConfigChanged(int32 Selected_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "ControllerPlatformConfigChanged");

	Params::TabGamePadConfig_C_ControllerPlatformConfigChanged Parms{};

	Parms.Selected_Index = Selected_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TabGamePadConfig.TabGamePadConfig_C.UpdateOptionsTab
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::UpdateOptionsTab()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "UpdateOptionsTab");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Gamepad Config Changed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Selected_Index                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTabGamePadConfig_C::Gamepad_Config_Changed(int32 Selected_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Gamepad Config Changed");

	Params::TabGamePadConfig_C_Gamepad_Config_Changed Parms{};

	Parms.Selected_Index = Selected_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TabGamePadConfig.TabGamePadConfig_C.CenterOnTab
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::CenterOnTab()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "CenterOnTab");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Configuration Changed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Selected_Index                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTabGamePadConfig_C::Configuration_Changed(int32 Selected_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Configuration Changed");

	Params::TabGamePadConfig_C_Configuration_Changed Parms{};

	Parms.Selected_Index = Selected_Index;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTabGamePadConfig_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Initialize Data
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::Initialize_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Initialize Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Update Data
// (Public, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::Update_Data()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Update Data");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.Handle Mode Toggled
// (Public, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::Handle_Mode_Toggled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "Handle Mode Toggled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TabGamePadConfig.TabGamePadConfig_C.HandleGamepadMappingInfoChange
// (Public, BlueprintCallable, BlueprintEvent)

void UTabGamePadConfig_C::HandleGamepadMappingInfoChange()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TabGamePadConfig_C", "HandleGamepadMappingInfoChange");

	UObject::ProcessEvent(Func, nullptr);
}

}

