#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamID_Lime

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TeamID_Lime.TeamID_Lime_C
// 0x0000 (0x0038 - 0x0038)
class UTeamID_Lime_C final : public UFortTeamIdentification
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamID_Lime_C">();
	}
	static class UTeamID_Lime_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamID_Lime_C>();
	}
};
static_assert(alignof(UTeamID_Lime_C) == 0x000008, "Wrong alignment on UTeamID_Lime_C");
static_assert(sizeof(UTeamID_Lime_C) == 0x000038, "Wrong size on UTeamID_Lime_C");

}

