#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusPowerMinusSMinusS

#include "Basic.hpp"

#include "TextStyleMinusPowerMinusS_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Power-S-S.TextStyle-Power-S-S_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyleMinusPowerMinusSMinusS_C final : public UTextStyleMinusPowerMinusS_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Power-S-S_C">();
	}
	static class UTextStyleMinusPowerMinusSMinusS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusPowerMinusSMinusS_C>();
	}
};
static_assert(alignof(UTextStyleMinusPowerMinusSMinusS_C) == 0x000008, "Wrong alignment on UTextStyleMinusPowerMinusSMinusS_C");
static_assert(sizeof(UTextStyleMinusPowerMinusSMinusS_C) == 0x0000D0, "Wrong size on UTextStyleMinusPowerMinusSMinusS_C");

}

