#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusMessageCenterMinusDescription

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-MessageCenter-Description.TextStyle-MessageCenter-Description_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyleMinusMessageCenterMinusDescription_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-MessageCenter-Description_C">();
	}
	static class UTextStyleMinusMessageCenterMinusDescription_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusMessageCenterMinusDescription_C>();
	}
};
static_assert(alignof(UTextStyleMinusMessageCenterMinusDescription_C) == 0x000008, "Wrong alignment on UTextStyleMinusMessageCenterMinusDescription_C");
static_assert(sizeof(UTextStyleMinusMessageCenterMinusDescription_C) == 0x0000D0, "Wrong size on UTextStyleMinusMessageCenterMinusDescription_C");

}

