#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusMMinusB

#include "Basic.hpp"

#include "TextStyleMinusBaseMinusM_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-M-B.TextStyle-Base-M-B_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyleMinusBaseMinusMMinusB_C : public UTextStyleMinusBaseMinusM_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-M-B_C">();
	}
	static class UTextStyleMinusBaseMinusMMinusB_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusMMinusB_C>();
	}
};
static_assert(alignof(UTextStyleMinusBaseMinusMMinusB_C) == 0x000008, "Wrong alignment on UTextStyleMinusBaseMinusMMinusB_C");
static_assert(sizeof(UTextStyleMinusBaseMinusMMinusB_C) == 0x0000D0, "Wrong size on UTextStyleMinusBaseMinusMMinusB_C");

}

