#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-XS-HUD-DBNOBarMax.TextStyle-Base-XS-HUD-DBNOBarMax_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Base-XS-HUD-DBNOBarMax_C">();
	}
	static class UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C>();
	}
};
static_assert(alignof(UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C) == 0x000008, "Wrong alignment on UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C");
static_assert(sizeof(UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C) == 0x0000D0, "Wrong size on UTextStyleMinusBaseMinusXSMinusHUDMinusDBNOBarMax_C");

}

