#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusSignInPageMinusS

#include "Basic.hpp"

#include "TextStyleMinusBaseParent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-SignInPage-S.TextStyle-SignInPage-S_C
// 0x0000 (0x00D0 - 0x00D0)
class UTextStyleMinusSignInPageMinusS_C final : public UTextStyleMinusBaseParent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-SignInPage-S_C">();
	}
	static class UTextStyleMinusSignInPageMinusS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusSignInPageMinusS_C>();
	}
};
static_assert(alignof(UTextStyleMinusSignInPageMinusS_C) == 0x000008, "Wrong alignment on UTextStyleMinusSignInPageMinusS_C");
static_assert(sizeof(UTextStyleMinusSignInPageMinusS_C) == 0x0000D0, "Wrong size on UTextStyleMinusSignInPageMinusS_C");

}

