#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XpBoostQuantities

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass XpBoostQuantities.XpBoostQuantities_C
// 0x0020 (0x0258 - 0x0238)
class UXpBoostQuantities_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0238(0x0008)(Transient, DuplicateTransient)
	class UCommonTextBlock*                       TextBoostXPQuant;                                  // 0x0240(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TextDBXPQuant;                                     // 0x0248(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TextNormalXPQuant;                                 // 0x0250(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_XpBoostQuantities(int32 EntryPoint);
	void Xp_Boost_Changed(int32 BoostAmount);
	void HandleAccountUpdate(const struct FFortPublicAccountInfo& NewInfo);
	void Construct();
	void UpdateXPQuantitiesInfo();
	int32 ScaledBoostBalance(int32 AmountToLevel);
	int32 ScaledRestBalance(int32 AmountToLevel);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"XpBoostQuantities_C">();
	}
	static class UXpBoostQuantities_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UXpBoostQuantities_C>();
	}
};
static_assert(alignof(UXpBoostQuantities_C) == 0x000008, "Wrong alignment on UXpBoostQuantities_C");
static_assert(sizeof(UXpBoostQuantities_C) == 0x000258, "Wrong size on UXpBoostQuantities_C");
static_assert(offsetof(UXpBoostQuantities_C, UberGraphFrame) == 0x000238, "Member 'UXpBoostQuantities_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UXpBoostQuantities_C, TextBoostXPQuant) == 0x000240, "Member 'UXpBoostQuantities_C::TextBoostXPQuant' has a wrong offset!");
static_assert(offsetof(UXpBoostQuantities_C, TextDBXPQuant) == 0x000248, "Member 'UXpBoostQuantities_C::TextDBXPQuant' has a wrong offset!");
static_assert(offsetof(UXpBoostQuantities_C, TextNormalXPQuant) == 0x000250, "Member 'UXpBoostQuantities_C::TextNormalXPQuant' has a wrong offset!");

}

